$(document).ready ->
  # constructs the suggestion engine
  engine = new Bloodhound(
    datumTokenizer: Bloodhound.tokenizers.obj.whitespace('name')
    queryTokenizer: Bloodhound.tokenizers.whitespace
    prefetch: 'select_users.json')
  # kicks off the loading/processing of `local` and `prefetch`
  engine.initialize()
  $('#typeahead').typeahead({
    hint: true
    highlight: true
    minLength: 1
  },
    name: 'potential_contributors'
    source: engine.ttAdapter()
    displayKey: 'name').bind 'typeahead:selected', (obj, datum, name) ->
    $.ajax
      url: 'add_collaborator'
      type: 'PUT'
      dataType: 'json'
      data:
        username: datum.name
        role: 'contributor'
      success: (data) ->
        if data['user']
          user_html = $('<tr><td>' + data['user']['username'] + '</td><td>' + data['user']['name'] + '</td><td><a class=\'btn btn-primary btn-large\' rel=\'nofollow\' data-method=\'put\' href=\'' + data['delete_url'] + '\'>Remove</a></td></tr>')
          $('#contributors').append user_html
          $('#select_user').val("")
        return
    return
  return

# ---
# generated by js2coffee 2.0.4